export const Stars = [
    {
        id: 0,
        isSparkle: false,
        iconSize: 28,
        size: 800,
        rotation: -72,
        shouldOrbit: true,
        orbitDuration: '42s',
        shouldSpin: true,
        spinDuration: '6s',
    },
    {   
        id: 1,
        isSparkle: false,
        iconSize: 12,
        size: 550,
        rotation: 20,
        shouldOrbit: true,
        orbitDuration: '36s',
        shouldSpin: true,
        spinDuration: '6s',
    },
    {   
        id: 2,
        isSparkle: false,
        iconSize: 20,
        size: 690,
        rotation: 98,
        shouldOrbit: true,
        orbitDuration: '38s',
        shouldSpin: true,
        spinDuration: '6s',
    },
    {   
        id: 3,
        isSparkle: false,
        iconSize: 8,
        size: 430,
        rotation: 98,
        shouldOrbit: true,
        orbitDuration: '31s',
        shouldSpin: true,
        spinDuration: '6s',
    },
    {   
        id: 4,
        isSparkle: true,
        iconSize: 8,
        size: 430,
        rotation: -14,
        shouldOrbit: true,
        orbitDuration: '30s',
        shouldSpin: true,
        spinDuration: '3s',
    },
    {   
        id: 5,
        isSparkle: true,
        iconSize: 5,
        size: 440,
        rotation: 79,
        shouldOrbit: true,
        orbitDuration: '32s',
        shouldSpin: true,
        spinDuration: '3s',
    },
    {   
        id: 6,
        isSparkle: true,
        iconSize: 10,
        size: 530,
        rotation: 178,
        shouldOrbit: true,
        orbitDuration: '34s',
        shouldSpin: true,
        spinDuration: '3s',
    },
    {   
        id: 7,
        isSparkle: true,
        iconSize: 12,
        size: 710,
        rotation: 144,
        shouldOrbit: true,
        orbitDuration: '40s',
        shouldSpin: true,
        spinDuration: '3s',
    },
    {   
        id: 8,
        isSparkle: false,
        iconSize: 20,
        size: 760,
        rotation: 50,
        shouldOrbit: true,
        orbitDuration: '44s',
        shouldSpin: true,
        spinDuration: '6s',
    },
];

export const HeroRings: string[] = ['620px', '820px', '1020px', '1220px'];